services:
  app:
    image: pretrip
    env_file:
      - .env
    build:
      context: ./
      target: ${APP_TARGET}
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    restart: on-failure
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/flare
    expose:
      - ${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: on-failure
    volumes:
      - /Users/belendia/.postgres_flare:/var/lib/postgresql/data
    command: -p ${DB_PORT}
